### ISSUE TITLE
Screenshot naming does not match format of Jasmine2HtmlReporter output

### ISSUE THREAD

**Issue by jamesomorodion** [abhishekkyd/protractor-html-reporter-2#1]
When fix screenshot name is applied to Jasmine2HtmlReporter, output of screenshot is named "test-case-name.png". No browser or Test Suite prefix, and test case name space is sanitized to replace spaces with hyphen.

This reporter does not sanitize to match. It adds browser and test suite as prefix and test case name spaces aren't replaced with hyphens. 

For compatibility and flexibility reasons I believe we need the ability to specify a replace character, and options to exclude browser and test suite prefix.

I can write a suggested fix if needed, unless this wasn't meant to support this convention.

The below name manipulation logic needs update:

`//get test cases screenshots names (on failure only)`
`          if (testCasesResults[j] != 'Failed' && report.screenshotsOnlyOnFailure) {`
`            screenshotsNamesOnFailure.push('None');`
`          } else {`
`            if (report.modifiedSuiteName) {`
`              screenshotsNamesOnFailure.push(report.browser +'-'+ suite.name.substring(suite.name.indexOf(".")+1) + ' ' + testCasesNames[j] + '.png');`
`              // screenshotsNamesOnFailure.push(report.browser +'-'+ testSuites[i].attr.name.substring(testSuites[i].attr.name.indexOf(".")+1) + ' ' + testCasesNames[j] + '.png');`
`            }`
`            else {`
`              screenshotsNamesOnFailure.push(report.browser +'-'+ suite.name + ' ' + testCasesNames[j] + '.png');`
`            }`
`          }`

**Comment by abhishekkyd** [comment]
@jamesomorodion Thanks for suggestion and fix. I will test the fix and will merge.

**Comment by jamesomorodion** [comment]
Thanks @abhishekkyd I added a tiny bit more logic for backwards compatibility.

**Comment by jamesomorodion** [comment]
hey @abhishekkyd just checking on this issue :) 
thanks!

**Comment by abhishekkyd** [comment]
Fix merged from pull request https://github.com/abhishekkyd/protractor-html-reporter-2/pull/2

**Comment by abhishekkyd** [comment]
@jamesomorodion Thanks, merged the code and published new version on NPM as well
