### ISSUE TITLE
Is there way to get the consolidated results for the execution of mulitple spec files in a suite

### ISSUE THREAD

**Issue by sambasiva029** [abhishekkyd/protractor-html-reporter-2#4]
Hi,

Is there a possibility to get a consolidated HTML report for the SUITE execution using consolidateAll : true 
if yes please let us know what has to be used?

**Comment by jamesomorodion** [comment]
@sambasiva029 If I understand correctly, you have a few outputs and you want it consolidated with a single config attribute. 

Currently I don't think there's a way to do that currently, you have to iterate through your output dir and manually include all files in your report.
