### ISSUE TITLE
Alternative screenshot naming not working correctly

### ISSUE THREAD

**Issue by jamesomorodion** [abhishekkyd/protractor-html-reporter-2#5]
Hey so due to variable name missing a letter the alternative screenshot naming does not work to maintain compatibility with Jasmine 2 screenshot naming convention. 

Please review PR: https://github.com/abhishekkyd/protractor-html-reporter-2/pull/3

Thank You @abhishekkyd

**Comment by abhishekkyd** [comment]
fixed in: https://github.com/abhishekkyd/protractor-html-reporter-2/pull/3
